spring:
  profiles:
    active: local
    default: local

  devtools:
    livereload:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 34.127.61.11 # 로컬에서 테스트 할 때는 localhost 사용
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000

oauth2:
  client:
    registration:
      naver:
        client-id: ${NAVER_CLIENT_ID}
        client-secret: ${NAVER_CLIENT_SECRET}
        login-redirect-uri: ${NAVER_LOGIN_CALLBACK_URL}
        signup-redirect-uri: ${NAVER_SIGNUP_CALLBACK_URL}
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        login-redirect-uri: ${KAKAO_LOGIN_CALLBACK_URL}
        signup-redirect-uri: ${KAKAO_SIGNUP_CALLBACK_URL}
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        login-redirect-uri: ${GOOGLE_LOGIN_CALLBACK_URL}
        signup-redirect-uri: ${GOOGLE_SIGNUP_CALLBACK_URL}
    provider:
      naver:
        authorization-uri: ${NAVER_LOGIN_API}
        token-uri: ${NAVER_TOKEN_API}
        user-info-uri: ${NAVER_USER_PROFILE_API}
        authorization-grant-type: authorization_code
      kakao:
        authorization-uri: ${KAKAO_LOGIN_API}
        token-uri: ${KAKAO_TOKEN_API}
        user-info-uri: ${KAKAO_USER_PROFILE_API}
        authorization-grant-type: authorization_code
      google:
        authorization-uri: ${GOOGLE_LOGIN_API}
        token-uri: ${GOOGLE_TOKEN_API}
        user-info-uri: ${GOOGLE_USER_PROFILE_API}
        authorization-grant-type: authorization_code
jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiresin: ${JWT_ACCESS_TOKEN_EXPIRES_IN}
    refresh-token-expiresin: ${JWT_REFRESH_TOKEN_EXPIRES_IN}

client:
  scheme: https
  domain: ludoapi.store
  url: ${client.scheme}://${client.domain}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: ${PORT}
