spring:

  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/ludo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

oauth2:
  client:
    registration:
      naver:
        client-id: ${NAVER_CLIENT_ID}
        client-secret: ${NAVER_CLIENT_SECRET}
        login-redirect-uri: ${NAVER_LOGIN_CALLBACK_URL}
        signup-redirect-uri: ${NAVER_SIGNUP_CALLBACK_URL}
        authorization-grant-type: code
      kakao:
        client-id: "ed54c5ca30a1f77a6a017194159af556"
        client-secret: "0lortXKR3XPY1KUSsRnrWVMdyl0Csz9O"
        signup-redirect-uri: "http://localhost:8080/auth/signup/kakao/callback"
        login-redirect-uri: "http://localhost:8080/auth/login/kakao/callback"
        authorization-grant-type: code

    provider:
      naver:
        authorization-uri: ${NAVER_LOGIN_API}
        token-uri: ${NAVER_TOKEN_API}
        user-info-uri: ${NAVER_USER_PROFILE_API}
      kakao:
        authorization-uri: "https://kauth.kakao.com/oauth/authorize?response_type=%s&client_id=%s&redirect_uri=%s"
        token-uri: "https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id=%s&redirect_uri=%s&code=%s&client_secret=%s"
        user-info-uri: "https://kapi.kakao.com/v2/user/me"


jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiresin: ${JWT_ACCESS_TOKEN_EXPIRES_IN}
