spring:

  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/ludo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    show-sql: true

    defer-datasource-initialization: true

jwt:
  secret-key: "7J206rKD7J2AIO2MqOyKpOybjOuTnCDsnoXri4jri6Qu"
  refresh-token-validity-in-seconds: 1209600
  access-token-validity-in-seconds: 43200

oauth:
  kakao:
    callback-url: "https://kauth.kakao.com/oauth/authorize?response_type=%s&client_id=%s&redirect_uri=%s"
    response-type: "code"
    client-id: "ed54c5ca30a1f77a6a017194159af556"
    client-secret: "0lortXKR3XPY1KUSsRnrWVMdyl0Csz9O"
    signup-redirect-url: "http://localhost:8080/auth/signup/kakao/callback"
    login-redirect-url: "http://localhost:8080/auth/login/kakao/callback"
    token-url: "https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id=%s&redirect_uri=%s&code=%s&client_secret=%s"
    user-info-url: "https://kapi.kakao.com/v2/user/me"

